version: '3'
services:
  app:
    container_name: singularity-pro
    image: singularitynetwork/singularity-pro
    ports:
      - "3002:3002"
    volumes:
      - ./data:/data
      - ./config:/config
    environment:
      - NODE_ENV=prodution

